# Generated by Django 5.2.7 on 2025-11-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorOnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False)),
                ('document_uploaded', models.BooleanField(default=False)),
                ('pickup_address', models.BooleanField(default=False)),
                ('product_variant', models.BooleanField(default=False)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='vendors.vendor')),
            ],
        ),
    ]
