# Generated by Django 5.2.7 on 2025-11-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendoraccesstoken',
            old_name='acess_token',
            new_name='access_token',
        ),
        migrations.AlterField(
            model_name='vendormobileotp',
            name='phone',
            field=models.CharField(unique=True),
        ),
    ]
