# Generated by Django 5.2.7 on 2025-11-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMobileOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('isUsed', models.BooleanField(default=False)),
                ('otp_updated', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
