# Generated by Django 5.2.7 on 2025-11-13 00:59

import django.db.models.deletion
import vendors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendormobileotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=300)),
                ('address_line_2', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=9, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signeture', models.ImageField(upload_to=vendors.models.signeture_image_upload_path)),
                ('alt_text_signeture', models.CharField(blank=True, max_length=200, null=True)),
                ('gst_certificate', models.FileField(upload_to=vendors.models.gst_certificate_upload_path)),
                ('alt_text_gst_certificate', models.CharField(blank=True, max_length=200, null=True)),
                ('verified_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VendorAddressTable',
        ),
        migrations.RenameField(
            model_name='vendoremailotp',
            old_name='otp_updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='vendormobileotp',
            old_name='otp_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pickupaddress',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='vendors.vendor'),
        ),
        migrations.AddField(
            model_name='vendordocument',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendors.vendor'),
        ),
    ]
