# Generated by Django 5.2.7 on 2025-12-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendoronboardingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_products', models.PositiveIntegerField(default=0)),
                ('not_verfied_products', models.PositiveIntegerField(default=0)),
                ('inactive_products', models.PositiveIntegerField(default=0)),
                ('total_order_items', models.PositiveIntegerField(default=0)),
                ('total_delivered_items', models.PositiveIntegerField(default=0)),
                ('total_cancelled_items', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='vendors.vendor')),
            ],
        ),
    ]
