# Generated by Django 5.2.7 on 2025-12-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendorstate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VendorState',
            new_name='VendorStats',
        ),
    ]
