# Generated by Django 5.2.7 on 2025-12-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_rename_vendorstate_vendorstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstats',
            name='total_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
