# Generated by Django 5.2.7 on 2025-12-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorstats_total_earning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorstats',
            old_name='not_verfied_products',
            new_name='not_verified_products',
        ),
    ]
