# Generated by Django 5.2.7 on 2025-12-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_rename_not_verfied_products_vendorstats_not_verified_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorStats',
        ),
    ]
