# Generated by Django 5.2.7 on 2025-11-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='attribute_value',
            field=models.CharField(default='value', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='attribute_name',
            field=models.CharField(default='name', max_length=50),
        ),
    ]
