# Generated by Django 5.2.7 on 2025-11-04 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_attribute_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catagories',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
