# Generated by Django 5.2.7 on 2025-11-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_catagory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
