# Generated by Django 5.2.7 on 2025-11-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_is_delete_alter_productvariant_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
