# Generated by Django 5.2.7 on 2025-11-10 16:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='const_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
