# Generated by Django 5.2.7 on 2025-11-10 18:43

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_const_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ImageField(upload_to=products.models.variant_image_upload_path),
        ),
    ]
