# Generated by Django 5.2.7 on 2025-11-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productvariantimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantimage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
