# Generated by Django 5.2.7 on 2025-12-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productvariantimage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='is_verifed',
            field=models.BooleanField(default=False),
        ),
    ]
