# Generated by Django 5.2.7 on 2025-10-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='created_at',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='otp_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
