# Generated by Django 5.2.7 on 2025-10-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_emailotp_created_at_emailotp_otp_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
    ]
