# Generated by Django 5.2.7 on 2025-11-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_checkoutsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='commission_ammount',
            new_name='commission_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='tax_ammount',
            new_name='tax_amount',
        ),
    ]
