# Generated by Django 5.2.7 on 2025-11-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_commission_ammount_orderitem_commission_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='refunded_ammount',
            new_name='refunded_amount',
        ),
    ]
